version: '3.4'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/data:/data
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb/db:/data/db
  # pemap-api:
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - redis
  #     - mongodb
